article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "articles"
urlpatterns = [
    path("dashboard/",views.dashboard,name = "dashboard"),
    path("addarticle/",views.addarticle,name = "addarticle"),
    path("article/<int:id>",views.detail,name = "detail"),
    path("update/<int:id>",views.updateArticle,name = "update"),
    path("delete/<int:id>",views.deleteArticle,name = "delete"),
    path("",views.articles,name = "articles"),
    path("comment/<int:id>",views.addComment,name = "comment"),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from blog import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('about/',views.about,name="about"),
    path('articles/',include("article.urls"),name = "articles"),
    path("user/", include("user.urls"), name="user")
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginuser,name = "loginuser"),
    path('logout/',views.logoutuser,name = "logoutuser"),

]

article/models.py
from django.db import models
from django.db.models.fields import CharField, TextField
from django.db.models.fields.related import ForeignKey
from ckeditor.fields import RichTextField
from django_resized import ResizedImageField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name="Yazıçı")
    title = models.CharField(max_length=30,verbose_name="Başlıq")
    content = RichTextField(verbose_name="Mətin")
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Hazırlandığı tarix")
    article_photo = ResizedImageField(size = [700,450],blank = True, null = True, verbose_name="Şəkil əlavə et")
    
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE,verbose_name="Meqale",related_name="comments")
    comment_author = models.CharField(max_length=50,verbose_name="Ad")
    comment_content =models.CharField(max_length=400,verbose_name="Rəy")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_photo"]

user/forms.py
from django import forms
from django.forms.fields import CharField
from django.forms.widgets import PasswordInput


class LoginForm(forms.Form):
    username=  forms.CharField(max_length=30,label="İstifadəçi adı:")
    password = forms.CharField(max_length=40,label="Şifrə:",widget=PasswordInput)
    


class RegisterForm(forms.Form):
    username = CharField(max_length=20,label="İstifadəçi adı:")
    password = CharField(max_length=25,label="Şifrə",widget=forms.PasswordInput)
    confirm  = CharField(max_length=25,label="Şifrəni təkrarlayın:",widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if confirm and password and password != confirm:
            raise forms.ValidationError("Şifrələr eyni deyil.")
    
        values = {
            "username": username,
            "password": password
        }

article/views.py
import article
from django.db.models import fields
from django.http.response import HttpResponse 
from django.shortcuts import get_object_or_404, redirect, render
from .forms import ArticleForm
from django.contrib import messages
from .models import Article, Comment
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.



def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

@login_required(login_url="user:loginuser")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context={
        "articles":articles
    }
    return render(request,"dashboard.html",context)
@login_required(login_url= "user:loginuser")
def addarticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():

        article = form.save(commit=False)
        article.author = request.user

        article.save()
        messages.success(request,"Məqalə uğurla əlavə edildi.")
        return redirect("index")

    

    return render(request,"addarticle.html",{"form":form})

def detail(request,id):

    #article = Article.objects.filter(id = id).first()  
    article = get_object_or_404(Article,id = id)
    comments= article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})

@login_required(login_url = "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user

        article.save()
        messages.success(request,"Məqalə uğurla əlavə edildi.")
        return redirect("index")

    return render(request,"update.html",{"form":form})

@login_required(login_url= "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article, id = id)

    article.delete()

    messages.success(request,"Məqalə uğurla silindi")

    return redirect("articles:dashboard")

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        
        return render(request,"articles.html",{"articles":articles})


    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})

def addComment(request,id):
    article = get_object_or_404(Article, id = id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author,comment_content = comment_content)
        newComment.article = article

        newComment.save()
    

    return redirect(reverse("articles:detail",kwargs = {"id":id}))

user/views.py
from django.http.response import HttpResponse
from django.shortcuts import render,redirect
from .forms import LoginForm, RegisterForm
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth import login, authenticate,logout

# Create your views here.

def register(request):
        
        form = RegisterForm(request.POST or None)
        if form .is_valid():
            
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            newUser = User(username = username)
            newUser.set_password(password)

            newUser.save()
            login(request,newUser)
            messages.success(request, 'Qeydiyyat uğurla tamamlandı.')

            return redirect("index")
        context = {
            "form":form
        }
        return render(request,"register.html",context)    
  
def loginuser(request):
   
    form = LoginForm(request.POST or None)
    context = {
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user =authenticate(username = username, password = password)

        if user is None:
            messages.info(request,"İstifadəçi adı və ya şifrə yalnışdır.") 
            return render(request,"login.html",context)
        
        messages.success(request,"Giriş uğurla baş verdi")
        login(request,user)
        return redirect("index")

    return render(request,"login.html",context)    

def logoutuser(request):
    logout(request)
    messages.success(request,"Sistemdən uğurla çıxıldı.")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}

{% block body %}
<h3>Haqqımızda</h3>
<hr>
İngilis dilindən tərcümə edilib-Python, şərh olunan yüksək səviyyəli ümumi məqsədli bir proqramlaşdırma dilidir. Python'un dizayn fəlsəfəsi, nəzərəçarpacaq bir girintinin nəzərə çarpan istifadəsi ilə kodun oxunaqlılığını vurğulayır.
<hr>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<form method="post" class="uniForm" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Məqalə əlavə et:</h3>
    <hr>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}
                {{form|crispy}}
                
                <button class = "btn btn-danger"type ="submit">Göndər</button>
            </form>
        </div>
      </div>
</form>



  
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% block body %}
<h3>Məqalələr</h3>
<hr>
<!-- Search form -->
<form >
   {% csrf_token %}
  <input type="text" name = "keyword" maxlength="64" placeholder="Axtar..">
  <button type="submit" class="btn btn-danger">Axtar</button>
</form>
{% if articles %}
  {% for article in articles  %}
  <div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
        
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">Yazıçı: {{article.author.username}}</div>
                </header>
                <hr>
                <!-- Preview image figure-->
                {% if article.article_photo %}
                    <img src="{{article.article_photo.url}}" class="img-responsive">
      
                {% endif %}
                
            
                <!-- Post content-->
                <p>Tarix: {{article.created_date}}</p>
                <hr>
                <div>{{article.content|safe|truncatewords:100}}</div>
                <a href="/articles/article/{{article.id}}" style="float: right;" class="btn btn-danger">Davamını oxu</a>
                
                
            </article>
    
        </div>
        </div>
    </div>


  {% endfor %}
{% else %}
  <div class = "alert alert-danger">Bu bloqda heç bir məqalə yoxdur.</div>
{% endif %}



{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Idarəetmə Paneli</h3>
<hr>
<p>
    Xoş gəldiniz, <small>{{request.user.username}}</small>
</p> 

<a href="{% url 'articles:addarticle' %}"class = "btn btn-danger">Məqalə əlavə et</a>
<hr>
{% if articles %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Başlıq</th>
        <th scope="col">Yazar</th>
        <th scope="col">Tarix</th>
        <th scope="col">Yenilə</th>
        <th scope="col">Sil</th>
      </tr>
    </thead>
    <tbody>
        {% for article in articles %}
        <tr>
          <th scope = "row">{{article.id}}</th>
          <td><a href="{% url 'articles:detail' article.id %}">{{article.title}}</a></td>
          <td>{{article.author}}</td>
          <td>{{article.created_date}}</td>
          <td><a href="{% url 'articles:update' article.id %}"class = "btn btn-danger">Yenilə</a></td>
          <td><a href="{% url 'articles:delete' article.id %}"class = "btn btn-danger">Sil</a></td>
        </tr>
        {% endfor %}

     
    </tbody>
  </table>
{% else %}
  <div class = "alert alert-danger">Sizin heç bir məqaləniz yoxdur.</div>
{% endif %}




{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% block body %}
  <!-- Page content-->
  <div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">Yazıçı: {{article.author.username}}</div>
                </header>
                <hr>
                <!-- Preview image figure-->
                {% if article.article_photo %}
                    <img src="{{article.article_photo.url}}">
      
                {% endif %}
                
            
                <!-- Post content-->
                <p>Tarix: {{article.created_date}}</p>
                <hr>
                <div>{{article.content|safe}}</div>
                
                <hr>
                <h4>Rəylər</h4>
                <hr>
            {% if comments %}

                {% for comment in comments %}

                <div>
                    <div class="card">
                        <div class="cadfd-body textd-center">
                    
                        </div>
                        <div class="comment-widgets">
                            <!-- Comment Row -->
                            <div class="d-flex flex-row comment-row m-t-0">
                                <div class="p-2"><img src="https://openclipart.org/image/800px/4749" alt="user" width="50" class="rounded-circle"></div>
                                <div class="comment-text w-100">
                                    <h5 class="font-medium">{{comment.comment_author}}</h5><span class="m-b-15 d-block">{{comment.comment_content}}</span>
                                    <div class="comment-footer"> <span class="text-muted float-right">{{comment.comment_date}}</span></div><br>
                                </div>
                            </div> <!-- Card -->
                        </div>
                    </div>
                </div>
                <br>
                {% endfor %}
            
            {% else %}
              <div class="alert alert-danger">Bu məqalədə heç bir rəy yoxdur. İlki siz edə bilərsiniz :)</div>
            {% endif %}
            
            
            </article>
            <div class="card my-4">
                <h5 class = "card-header">Rəy Bildir</h5>
                <div class = "card-body">

                    <form method="POST" action="{% url 'articles:comment' article.id %}"  >
                        {% csrf_token %}
                        <form">
                            <div class="form-group">
                              <label for="formGroupExampleInput">Ad</label>
                              <input name="comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="Adınızı daxil edin...">
                            </div>
                          </form>

                        <div class = "form-group">
                            <label for="formGroupExampleInput">Rəy</label>
                            
                            <textarea name="comment_content" class = "form-control" rows="3" placeholder="Rəyi daxil edin..."></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Əlavə et</button>
                    </form>
                </div>
    
        </div>
        </div>
    </div>
  
{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">Django Bloq</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">Haqqımızda <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'articles:articles' %}">Məqalələr<span class="sr-only">(current)</span></a>
          </li>
      </ul>
      <ul class="navbar-nav ml-auto">

        
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:register' %}">Qeydiyyat <span class="sr-only">(current)</span></a>
          </li>

          {% if request.user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:logoutuser' %}">Çıxış<span class="sr-only">(current)</span></a>
          </li>
          
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'articles:dashboard' %}">İdarə etmə Paneli <span class="sr-only">(current)</span></a>
          </li>
        
          {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:loginuser' %}">Giriş <span class="sr-only">(current)</span></a>
          </li>
            
          {% endif %}
          
         
      
      </ul>
         
    </div>
  </nav>

templates/includes/posttemplate.html
  <!-- Page content-->
  <div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">Welcome to Blog Post!</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">Posted on January 1, 2021 by Start Bootstrap</div>
                    <!-- Post categories-->
                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
                </header>
                <!-- Preview image figure-->
                <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
                <!-- Post content-->
                <section class="mb-5">
                    <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the free human mind. Because it transforms who we are, how we live, and it gives us an understanding of our place in the universe.</p>
                    <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it are everywhere, so there's no reason to think that Earth would be unique in that regard. Whether of not the life became intelligent is a different question, and we'll see if we find that.</p>
                    <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and carry enough energy into our system to disrupt transportation, communication, the food chains, and that can be a really bad day on Earth.</p>
                    <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
                    <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic thoughts every day and I realized I could hold them to myself or share them with people who might be interested.</p>
                    <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened there because we're twirling knobs here on Earth without knowing the consequences of it. Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
                </section>
            </article>
            <!-- Comments section-->
            <section class="mb-5">
                <div class="card bg-light">
                    <div class="card-body">
                        <!-- Comment form-->
                        <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                        <!-- Comment with nested comments-->
                        <div class="d-flex mb-4">
                            <!-- Parent comment-->
                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                            <div class="ms-3">
                                <div class="fw-bold">Commenter Name</div>
                                If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                                <!-- Child comment 1-->
                                <div class="d-flex mt-4">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                                    </div>
                                </div>
                                <!-- Child comment 2-->
                                <div class="d-flex mt-4">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        When you put money directly to a problem, it makes a good headline.
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Single comment-->
                        <div class="d-flex">
                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                            <div class="ms-3">
                                <div class="fw-bold">Commenter Name</div>
                                When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
        <!-- Side widgets-->
        <div class="col-lg-4">
            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                        <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                    </div>
                </div>
            </div>
            <!-- Categories widget-->
            <div class="card mb-4">
                <div class="card-header">Categories</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                <li><a href="#!">Web Design</a></li>
                                <li><a href="#!">HTML</a></li>
                                <li><a href="#!">Freebies</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                <li><a href="#!">JavaScript</a></li>
                                <li><a href="#!">CSS</a></li>
                                <li><a href="#!">Tutorials</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Side widget-->
            <div class="card mb-4">
                <div class="card-header">Side Widget</div>
                <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
            </div>
        </div>
    </div>
</div>

templates/index.html
{% extends "layout.html" %}

{% block body %}
<div class="jumbotron text-center">
    <h3>Django bloquna xoş gəlmisiniz!</h3>
    <p>Bu bloq Django öyrənmək istəyənlər üçündür.</p>
</div>



<p>
    {% if request.user.is_authenticated %}
      Daxil olunub, {{request.user.username}}
    {% else %}
      Daxil olunmayıb
    {% endif %}
    

</p>











{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Django Bloq</title>
</head>
<body>
   {% include "includes/navbar.html" %}
   <div style="margin-top: 100px; margin-bottom: 100px;" class = "container">
            
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}


            {% if message.tags == "info" %}
        <div class="alert alert-danger">{{ message }}</div>

            {% else %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>

            {% endif %}
        


        {% endfor %}
    </ul>
    {% endif %}

    {% block body %}
  

    {% endblock body %}


   </div>

   <script src="{% static 'js/bootstrap.min.js' %}"></script>
   <script src="{% static 'js/query-3.6.0.min.js' %}"></script>
   <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<form method="post" class="uniForm">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Loqin:</h3>
    <hr>
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                
                <button class = "btn btn-danger"type ="submit">Daxil ol</button>
            </form>
        </div>
      </div>
</form>



{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}


<form method="post" class="uniForm">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Qeydiyyat:</h3>
    <hr>
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                
                <button class = "btn btn-danger"type ="submit">Təsdiq edin</button>
            </form>
        </div>
      </div>
</form>




{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<form method="post" class="uniForm">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Məqalə yenilə:</h3>
    <hr>
            <form method="post">
                {% csrf_token %}
                {{form.media}}
                {{form|crispy}}
                
                <button class = "btn btn-danger"type ="submit">Göndər</button>
            </form>
        </div>
      </div>
</form>



  
{% endblock body %}